export const cubieList = [
    {
        id: "w",
        type: "center",
        coords: { x: 0, y: -1, z: 0 },
        colors: {
            top: "white",
        },
    },
    {
        id: "y",
        type: "center",
        coords: { x: 0, y: 1, z: 0 },
        colors: {
            down: "yellow",
        },
    },
    {
        id: "r",
        type: "center",
        coords: { x: -1, y: 0, z: 0 },
        colors: {
            left: "red",
        },
    },
    {
        id: "o",
        type: "center",
        coords: { x: 1, y: 0, z: 0 },
        colors: { right: "orange" },
    },
    {
        id: "b",
        type: "center",
        coords: { x: 0, y: 0, z: 1 },
        colors: { front: "blue" },
    },
    {
        id: "g",
        type: "center",
        coords: { x: 0, y: 0, z: -1 },
        colors: { back: "green" },
    },
    {
        id: "wbr",
        type: "corner",
        coords: { x: -1, y: -1, z: 1 },
        colors: { top: "white", front: "blue", left: "red" },
    },
    {
        id: "wbo",
        type: "corner",
        coords: { x: 1, y: -1, z: 1 },
        colors: { top: "white", front: "blue", right: "orange" },
    },
    {
        id: "wgo",
        type: "corner",
        coords: { x: 1, y: -1, z: -1 },
        colors: { top: "white", back: "green", right: "orange" },
    },
    {
        id: "wgr",
        type: "corner",
        coords: { x: -1, y: -1, z: -1 },
        colors: { top: "white", left: "red", back: "green" },
    },
    {
        id: "wb",
        type: "edge",
        coords: { x: 0, y: -1, z: 1 },
        colors: { top: "white", front: "blue" },
    },
    {
        id: "wo",
        type: "edge",
        coords: { x: 1, y: -1, z: 0 },
        colors: { top: "white", right: "orange" },
    },
    {
        id: "wr",
        type: "edge",
        coords: { x: -1, y: -1, z: 0 },
        colors: { top: "white", left: "red" },
    },
    {
        id: "wg",
        type: "edge",
        coords: { x: 0, y: -1, z: -1 },
        colors: { top: "white", back: "green" },
    },
    {
        id: "og",
        type: "edge",
        coords: { x: 1, y: 0, z: -1 },
        colors: { right: "orange", back: "green" },
    },
    {
        id: "rg",
        type: "edge",
        coords: { x: -1, y: 0, z: -1 },
        colors: { left: "red", back: "green" },
    },
    {
        id: "rb",
        type: "edge",
        coords: { x: -1, y: 0, z: 1 },
        colors: { front: "blue", left: "red" },
    },
    {
        id: "bo",
        type: "edge",
        coords: { x: 1, y: 0, z: 1 },
        colors: { front: "blue", right: "orange" },
    },
    {
        id: "by",
        type: "edge",
        coords: { x: 0, y: 1, z: 1 },
        colors: { front: "blue", down: "yellow" },
    },
    {
        id: "gy",
        type: "edge",
        coords: { x: 0, y: 1, z: -1 },
        colors: { back: "green", down: "yellow" },
    },
    {
        id: "ry",
        type: "edge",
        coords: { x: -1, y: 1, z: 0 },
        colors: { left: "red", down: "yellow" },
    },
    {
        id: "oy",
        type: "edge",
        coords: { x: 1, y: 1, z: 0 },
        colors: { right: "orange", down: "yellow" },
    },
    {
        id: "ybr",
        type: "corner",
        coords: { x: -1, y: 1, z: 1 },
        colors: { front: "blue", down: "yellow", left: "red" },
    },
    {
        id: "ybo",
        type: "corner",
        coords: { x: 1, y: 1, z: 1 },
        colors: {
            front: "blue",
            down: "yellow",
            right: "orange",
        },
    },
    {
        id: "ygr",
        type: "corner",
        coords: { x: -1, y: 1, z: -1 },
        colors: { back: "green", down: "yellow", left: "red" },
    },
    {
        id: "ygo",
        type: "corner",
        coords: { x: 1, y: 1, z: -1 },
        colors: {
            back: "green",
            down: "yellow",
            right: "orange",
        },
    },
];
